version: "3.8"
services: 
    proxy:
        build: 
            context: ./
            dockerfile: ./production/dockerfile
        networks: 
            - app
        ports:
            - "80:80"
            - "443:443"
networks: 
    app:
        external: true